name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  deep-sea-stories:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deep-sea-stories

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Enable corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ./deep-sea-stories/package.json
          cache: yarn
          cache-dependency-path: ./deep-sea-stories/yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Run format
        run: yarn format:check

      - name: Run lint
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Run backend tests
        run: yarn workspace backend test
